[package]
name = "driver-cp2130"
version = "0.3.3"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "libusb based driver for the CP2130 USB-SPI bridge by Silicon Labs"
repository = "https://github.com/ryankurte/rust-driver-cp2130"
keywords = [ "driver", "cp2130", "usb", "spi", "embedded" ]
license = "MPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
util = [ "structopt", "simplelog", "rand", "hex" ]
default = [ "util" ]

[dependencies]
rusb = { version = "0.5.5" }
libc = "0.2.66"
log = "0.4.8"
bitflags = "1.2.1"
byteorder = "1.3.2"
lazy_static = "1.4.0"

[dependencies.embedded-hal]
version = "0.2.3"
features = [ "unproven" ]

[dependencies.structopt]
version = "0.3.5"
optional = true

[dependencies.simplelog]
version = "0.7.4"
optional = true

[dependencies.hex] 
version = "0.4.0"
optional = true

[dependencies.rand] 
version = "0.7.2"
optional = true


[[bin]]
name = "cp2130-util"
path = "src/cli.rs"
required-features = [ "util" ]


[patch.crates-io]
embedded-hal = { git = "https://github.com/ryankurte/embedded-hal", branch = "feature/spi-transactions" }
libusb-sys = { git = "https://github.com/cmsd2/libusb-sys/" }
